### ISSUE TITLE
Update screenshot in README.md

### ISSUE THREAD

**Issue by FilippoBonazziSUSE** [openSUSE/openSUSEway#165]

**Comment by jubalh** [comment]
Great idea! I think this should then also be done for https://en.opensuse.org/Portal:OpenSUSEway

**Comment by FilippoBonazziSUSE** [comment]
> Great idea! I think this should then also be done for https://en.opensuse.org/Portal:OpenSUSEway

I can't figure out how to update the damn image on the opensuse wiki. Does someone else know how to do it?

**Comment by jubalh** [comment]
> Does someone else know how to do it?

Done by @denisok already :)

**Comment by FilippoBonazziSUSE** [comment]
No, I don't think that's right. It's still the old screenshot

**Comment by jubalh** [comment]
It's the one that has the geeko only at the active tab. And that uses test@localhost.
Also see: https://en.opensuse.org/index.php?title=File:Sway_openSUSE_15.2.png&action=history

**Comment by denisok** [comment]
actually - yes, I updated it. But looks like there is too much caching, it still shows old one for me. Opening new private tab - shows new image - hooray.

**Comment by FilippoBonazziSUSE** [comment]
Ah, indeed the old image was cached - ctrl-shift-r fixed it. I thought one of us was tripping but no ;)
